### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by bhatnathan** [FredrIQ/fiqrogue#3]
Peer review by Nathan Bhat and Tor Baumgardt
1. Short README.  You have made it clear how to install your program (although still a little confused on how to run it), but you should include features and a more in depth project discription.  For the uninitiated a term like "rouguelike" might not be in their vocabulary.
2. The commit messages are good and descriptive.  I'm wondering if you have small enough commits, being that you only have 17 commits, but I haven't looked into commit sizes.
3. While your current milestones are informative, it would be nice if you had milestones for a lot more of your tasks.  It isn't too clear what exactly has happened in the project, and what you aimed to get done.  Remember to connect your issues to each milestone accordingly.  You have two issues, and they are well done, however you should write issues for most everything you want to do in your program to keep track of what you need to do next.  I know you are not in a group so this does seem rather pointless, but good for learning.
4.  You have not included any bugs in issues.  We don't know if you have any bugs yet, so this might not matter.
5.  You have only use branch "master" and you have 0 pull requests so I won't comment on this.  Don't worry, it's the same for us ;)

**Comment by FredrIQ** [comment]
1. I will try to adress this shortly.
2. OK. Note that, while general practice is "1 commit = 1 logical change", I try to adhere to this only as long as the result still compiles. Thus, while most of my commits look OK imo according to this practice, one is questionable as a result (Commit 0418ccab8c9479ffd28c61e7b6c0ecd8008b816d )
3. I am not sure exactly how I can improve from what you've said, but I will try to think about it.
4. Issue #2 was a bug (not in fiqrogue, but in the curses library used, but a bug regardless), but was not labeled as such. I will try to label issues properly in the future.
5. I have had feature branches, but since the resulting commits has been linear without interleaving commits in master, git has been able to simply just fast-forward the history, making the branches redundant. I also remove feature branches when merged into master. The lack of pull requests makes sense since I work alone currently.
